In [285]:
import pandas as pd
from sklearn.model_selection import (
    train_test_split, StratifiedKFold, KFold, GroupKFold, RepeatedKFold, LeaveOneOut, TimeSeriesSplit,
    cross_val_score, cross_validate, validation_curve, learning_curve,
    GridSearchCV, RandomizedSearchCV
)
from sklearn.metrics import mean_absolute_error
from sklearn.datasets import fetch_california_housing
from sklearn.linear_model import LinearRegression

In [286]:
d = pd.read_csv(r"C:\Learning_ML\ML_Projects\Student\ai_student_impact_dataset (1).csv")
d.head()

   Student_ID Major_Category  ... Skill_Retention_Score  Burnout_Risk_Level
0      100001     Humanities  ...                 86.44                High
1      100002        Medical  ...                 69.39                 Low
2      100003       Business  ...                 73.93              Medium
3      100004       Business  ...                 63.58              Medium
4      100005           STEM  ...                100.00              Medium

[5 rows x 16 columns]

In [287]:
data = fetch_california_housing(as_frame=True)
data = data.frame
data.head()

   MedInc  HouseAge  AveRooms  ...  Latitude  Longitude  MedHouseVal
0  8.3252      41.0  6.984127  ...     37.88    -122.23        4.526
1  8.3014      21.0  6.238137  ...     37.86    -122.22        3.585
2  7.2574      52.0  8.288136  ...     37.85    -122.24        3.521
3  5.6431      52.0  5.817352  ...     37.85    -122.25        3.413
4  3.8462      52.0  6.281853  ...     37.85    -122.25        3.422

[5 rows x 9 columns]

In [288]:
X = data[["MedHouseVal"]]
Y = data["MedHouseVal"]

In [289]:
xtrain, xtest, ytrain, ytest = train_test_split(X, Y, test_size=0.1, random_state=42, shuffle=True)

In [ ]:
kf = KFold(n_splits=10, shuffle=True)

In [291]:
skf = StratifiedKFold(n_splits=8, shuffle=True)

In [292]:
group = GroupKFold(n_splits=10)

In [293]:
repeated = RepeatedKFold(n_splits=10, n_repeats=5)

In [294]:
loo = LeaveOneOut()

In [295]:
tss = TimeSeriesSplit(n_splits=4, max_train_size=5000, test_size=500, gap=0)

In [296]:
model = LinearRegression()
print(xtrain.shape)
print(ytrain.shape)
model.fit(xtrain, ytrain)
pred = model.predict(xtest)
mae = mean_absolute_error(ytest, pred)
print(mae)

(18576, 1)
(18576,)
1.6015397449219675e-15

In [297]:
cvc = cross_val_score(model, X, Y, cv = kf)

In [ ]:
cv = cross_validate()