In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import (
    OneHotEncoder, LabelEncoder, OrdinalEncoder, LabelBinarizer, 
    StandardScaler, MinMaxScaler
)
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
import joblib

In [3]:
data = pd.read_csv(r"C:\Learning_ML\ML_Projects\Student\ai_student_impact_dataset (1).csv")
data.head(10)

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
5,100006,STEM,Junior,3.449,6.50,Debugging/Troubleshooting,Beginner,1,False,14.19,4,Allowed_With_Citation,5,3.666,65.92,High
6,100007,STEM,Freshman,3.622,31.41,Summarizing_Reading,Advanced,5,True,13.11,8,Allowed_With_Citation,7,4.000,67.97,Medium
7,100008,Arts,Junior,2.746,5.33,Copywriting/Drafting,Intermediate,3,False,18.45,2,Actively_Encouraged,1,2.965,85.09,Medium
8,100009,Business,Sophomore,3.420,2.00,Debugging/Troubleshooting,Beginner,2,True,2.87,1,Strict_Ban,5,3.396,55.71,Medium
9,100010,Business,Sophomore,3.046,19.99,Debugging/Troubleshooting,Intermediate,2,True,12.49,3,Strict_Ban,8,2.978,87.18,High

In [4]:
data["Institutional_Policy"].unique()

array(['Allowed_With_Citation', 'Strict_Ban', 'Actively_Encouraged'],
      dtype=object)

In [5]:
data.describe()

,Student_ID,Pre_Semester_GPA,Weekly_GenAI_Hours,Tool_Diversity,Traditional_Study_Hours,Perceived_AI_Dependency,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score
count,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,125000.500000,3.146102,8.427752,2.80026,11.209271,3.505360,4.270760,3.349299,75.798125
std,14433.901067,0.478854,8.269490,1.18802,5.156426,1.820812,2.144066,0.495673,13.281626
min,100001.000000,1.183000,0.000000,1.00000,1.000000,1.000000,1.000000,1.000000,10.780000
25%,112500.750000,2.834000,2.390000,2.00000,7.560000,2.000000,3.000000,3.023750,66.820000
50%,125000.500000,3.210000,5.800000,3.00000,11.180000,3.000000,4.000000,3.421000,76.000000
75%,137500.250000,3.521000,11.720000,4.00000,14.710000,5.000000,6.000000,3.749000,85.190000
max,150000.000000,3.998000,40.000000,5.00000,35.860000,10.000000,10.000000,4.000000,100.000000

In [6]:
print(data.columns)
print(len(data.columns))

Index(['Student_ID', 'Major_Category', 'Year_of_Study', 'Pre_Semester_GPA',
       'Weekly_GenAI_Hours', 'Primary_Use_Case', 'Prompt_Engineering_Skill',
       'Tool_Diversity', 'Paid_Subscription', 'Traditional_Study_Hours',
       'Perceived_AI_Dependency', 'Institutional_Policy',
       'Anxiety_Level_During_Exams', 'Post_Semester_GPA',
       'Skill_Retention_Score', 'Burnout_Risk_Level'],
      dtype='object')
16

PREPROCESSING

In [7]:
scaler = StandardScaler()
psGPA = scaler.fit_transform(data[["Pre_Semester_GPA"]])
genai = scaler.fit_transform(data[["Weekly_GenAI_Hours"]])
studyhr = scaler.fit_transform(data[["Traditional_Study_Hours"]])
print(studyhr[:6])
# print(genai)

[[-0.59717753]
 [ 1.05514621]
 [-0.16664247]
 [ 0.77975892]
 [ 0.26001389]
 [ 0.57806682]]

In [8]:
ohe = OneHotEncoder()
puc = ohe.fit_transform(data[["Primary_Use_Case"]])
mc = ohe.fit_transform(data[["Major_Category"]])
print(mc[:6])
print(puc[:6])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (6, 5)>
  Coords	Values
  (0, 2)	1.0
  (1, 3)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 4)	1.0
  (5, 4)	1.0
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (6, 5)>
  Coords	Values
  (0, 0)	1.0
  (1, 3)	1.0
  (2, 4)	1.0
  (3, 0)	1.0
  (4, 1)	1.0
  (5, 1)	1.0

In [9]:
ord = OrdinalEncoder()
pes = ord.fit_transform(data[["Prompt_Engineering_Skill"]])
yos = ord.fit_transform(data[["Year_of_Study"]])
policy = ord.fit_transform(data[["Institutional_Policy"]])
# print(policy[:10])
# print(yos[:6])
# print(pes[:6])

In [10]:
lb = LabelBinarizer()
paid = lb.fit_transform(data[["Paid_Subscription"]])

Models

In [ ]:
m1 = DecisionTreeClassifier()
m2 = RandomForestClassifier()