In [1]:
import pandas as pd

import torch
import torch.nn as nn
import torch.optim as optim

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv("C:\\Learning_ML\\DL_projects\\breast_cancer\\Breast_Cancer.csv")
data.head(10)

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60,Alive
1,50,White,Married,T2,N2,IIIA,Moderately differentiated,2,Regional,35,Positive,Positive,14,5,62,Alive
2,58,White,Divorced,T3,N3,IIIC,Moderately differentiated,2,Regional,63,Positive,Positive,14,7,75,Alive
3,58,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,18,Positive,Positive,2,1,84,Alive
4,47,White,Married,T2,N1,IIB,Poorly differentiated,3,Regional,41,Positive,Positive,3,1,50,Alive
5,51,White,Single,T1,N1,IIA,Moderately differentiated,2,Regional,20,Positive,Positive,18,2,89,Alive
6,51,White,Married,T1,N1,IIA,Well differentiated,1,Regional,8,Positive,Positive,11,1,54,Alive
7,40,White,Married,T2,N1,IIB,Moderately differentiated,2,Regional,30,Positive,Positive,9,1,14,Dead
8,40,White,Divorced,T4,N3,IIIC,Poorly differentiated,3,Regional,103,Positive,Positive,20,18,70,Alive
9,69,White,Married,T4,N3,IIIC,Well differentiated,1,Distant,32,Positive,Positive,21,12,92,Alive

In [3]:
print(list(data.columns))

['Age', 'Race', 'Marital Status', 'T Stage', 'N Stage', '6th Stage', 'differentiate', 'Grade', 'A Stage', 'Tumor Size', 'Estrogen Status', 'Progesterone Status', 'Regional Node Examined', 'Reginol Node Positive', 'Survival Months', 'Status']

In [4]:
for i in ['Race', 'Marital Status', 'T Stage', 'N Stage', '6th Stage', 'differentiate', 'Grade', 'A Stage', 'Estrogen Status', 'Progesterone Status']:
    res = []
    for j in data[i]:
        if j not in res:
            res.append(j)
    print(i,' : ',res,' : ',len(res))

Race  :  ['White', 'Black', 'Other']  :  3
Marital Status  :  ['Married', 'Divorced', 'Single', 'Widowed', 'Separated']  :  5
T Stage  :  ['T1', 'T2', 'T3', 'T4']  :  4
N Stage  :  ['N1', 'N2', 'N3']  :  3
6th Stage  :  ['IIA', 'IIIA', 'IIIC', 'IIB', 'IIIB']  :  5
differentiate  :  ['Poorly differentiated', 'Moderately differentiated', 'Well differentiated', 'Undifferentiated']  :  4
Grade  :  ['3', '2', '1', 'anaplastic; Grade IV']  :  4
A Stage  :  ['Regional', 'Distant']  :  2
Estrogen Status  :  ['Positive', 'Negative']  :  2
Progesterone Status  :  ['Positive', 'Negative']  :  2

In [ ]:
X = data.drop(columns='Status')
Y = data['Status']
X.head()

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months
0,68,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60
1,50,White,Married,T2,N2,IIIA,Moderately differentiated,2,Regional,35,Positive,Positive,14,5,62
2,58,White,Divorced,T3,N3,IIIC,Moderately differentiated,2,Regional,63,Positive,Positive,14,7,75
3,58,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,18,Positive,Positive,2,1,84
4,47,White,Married,T2,N1,IIB,Poorly differentiated,3,Regional,41,Positive,Positive,3,1,50

In [6]:
label = LabelEncoder()
cat = X.select_dtypes(include='object').columns
for i in cat:
    X[i] = label.fit_transform(X[i])
X.head(10)

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months
0,68,2,1,0,0,0,1,2,1,4,1,1,24,1,60
1,50,2,1,1,1,2,0,1,1,35,1,1,14,5,62
2,58,2,0,2,2,4,0,1,1,63,1,1,14,7,75
3,58,2,1,0,0,0,1,2,1,18,1,1,2,1,84
4,47,2,1,1,0,1,1,2,1,41,1,1,3,1,50
5,51,2,3,0,0,0,0,1,1,20,1,1,18,2,89
6,51,2,1,0,0,0,3,0,1,8,1,1,11,1,54
7,40,2,1,1,0,1,0,1,1,30,1,1,9,1,14
8,40,2,0,3,2,4,1,2,1,103,1,1,20,18,70
9,69,2,1,3,2,4,3,0,0,32,1,1,21,12,92

In [7]:
print(cat)

Index(['Race', 'Marital Status', 'T Stage', 'N Stage', '6th Stage',
       'differentiate', 'Grade', 'A Stage', 'Estrogen Status',
       'Progesterone Status'],
      dtype='object')

In [8]:
xtrain, xtest, ytrain, ytest = train_test_split(X, Y, random_state=42, shuffle=True, test_size=0.1)

In [9]:
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)

In [10]:
le = LabelEncoder()
ytrain = le.fit_transform(ytrain)
ytest = le.fit_transform(ytest)

In [11]:
xtrain

array([[ 1.24239086,  0.40074056, -0.36107325, ...,  0.08590694,
         0.15857757,  0.77592289],
       [-1.54718755,  0.40074056, -0.36107325, ..., -0.16077746,
         0.15857757,  1.47768016],
       [ 1.01922459,  0.40074056, -0.36107325, ...,  1.07264454,
        -0.42477095,  1.08294169],
       ...,
       [ 0.34972577,  0.40074056,  1.51071806, ...,  2.05938215,
        -0.42477095, -1.15390959],
       [-0.65452246, -1.36887112, -0.36107325, ...,  1.56601335,
        -0.61922046,  1.34610067],
       [-0.09660678,  0.40074056, -0.36107325, ..., -0.03743526,
        -0.42477095,  1.43382033]], shape=(3621, 15))

In [12]:
ytrain
print(type(ytrain))
ytest
print(type(ytest))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [13]:
xtrain = torch.tensor(xtrain, dtype=torch.float32)
xtest = torch.tensor(xtest, dtype=torch.float32)
ytrain = torch.tensor(ytrain, dtype=torch.float32).reshape(-1,1)
ytest = torch.tensor(ytest, dtype=torch.float32).reshape(-1,1)

In [27]:
ytest.dtype

torch.float32

In [14]:
class NN_Model(nn.Module):
    def __init__(self, parameters):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(parameters, 4),
            nn.ReLU(),
            nn.Linear(4,1)
        )
    
    def forward(self, x):
        return self.network(x)

In [15]:
model = NN_Model(xtrain.shape[0])

In [16]:
epoch = 200
lr = 0.001

In [17]:
optimize = optim.Adam(model.parameters(), lr)

In [18]:
for ep in range(epoch):
    output = model(xtrain)
    loss = nn.BCELoss(output, ytrain)
    optimize.zero_grad
    loss.backward()
    optimize.step()
    if ep%25==0:
        print(f"For {ep} : {loss.items():.4f}")

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3621x15 and 3621x4)